### ISSUE TITLE
 In what direction should MPU be fixed to ESP or plate

### ISSUE THREAD

**Issue by svcvacv** [pgii/GyroMocapUE4#2]
Hello,
I follow the instructions to connect MPU and ESP with each other and set up the relevant software. The system can work smoothly. However, when the welding wire is fixed, it is difficult to install the MPU into the board or box in which direction it should be fixed. Therefore, it is difficult to install the MPU in the human body, so that the adapter plate is considered for effective test.I would  appreciate it if give a illustration of the direction of MPU installation.

Thanks,

**Comment by pgii** [comment]
Hi.
I'm not sure I understood your question correctly.
Attached a photo of the module to the repository page.
The axes and direction of rotation of the quaternion are changed after receiving data in an external program.

**Comment by svcvacv** [comment]
Oh thanks, its just this picture let me understand the direction  (^_^). nice work

**Comment by pgii** [comment]
It's my pleasure.)))
