### ISSUE TITLE
Sensor connection should be one click process, and motion recording function should be there

### ISSUE THREAD

**Issue by graphicsguru1991** [pgii/GyroMocapUE4#3]
**Issue:** While adding new sensor to a joint the process of creating new blueprints and making changes every time is a long process, it should be done in one click.

**Sugession 1:** There should be an option for motion recording and saving it in .FBX or .BVH will be more useful.

**Sugession 2** Option for adding custom characters will be a good idea i think.

**Comment by pgii** [comment]
This project is a demonstration of the sensor, UE4 is only a visualization of the result.
You can record motion with Sequence Recorder and export them to FBX for later use.

Custom characters  - is a really good idea, but it goes beyond the scope of the project.

Perhaps I will return to this project in the future, with new modules, because drifting on the current ones does not suit me very much and requires constant recalibration.

**Comment by graphicsguru1991** [comment]
sir have a question. How we can connect all the 17 sensors to the project? i mean how we gonna define all  sensor's position on body, and we need to calibrate each sensor separately or we can calibrate all sensors together?

i was just thinking if we can compile and make an .exe using UE4 to just connect, calibrate and use it without opening Unreal every time and export motion data on FBX or BVH format..

**Comment by pgii** [comment]
Yes, all sensors can be connected. The demo project shows a hand. The video shows the process of connecting the head. For the rest of the sensors, the process is similar. The controller has settings for the direction of rotation and replacement of axes for each sensor. The calibration process calibrates all sensors at the same time.

After connecting and configuring all sensors, you can create an exe file. To be honest, I haven't studied the issue of recording and exporting in a compiled project. But I don't think this is possible in blueprint. Most likely will have to implement it through C++.

**Comment by graphicsguru1991** [comment]
can you please help me with one thing... how we can use gloves for finger tracking and motion capturing both simultaneously?? how can we connect both together in unity?

**Comment by graphicsguru1991** [comment]
and is it also possible to connect multiple person on same Unreal project?

**Comment by pgii** [comment]
If you are talking about my projects, you can use it by simply combining them.
I can't say anything about the Unity.
Several persons can be used. But this requires significant improvements.
It seems to me easier to buy a ready-made system, because these projects were implemented out of curiosity and were never used in real conditions.

**Comment by graphicsguru1991** [comment]
i am unable to find this same esp32 and imu module which you have used.. will these modules (Link of the modules) work with this project or i will have to do changes on codes?? sorry sir i am 15yr old and very beginner in this, if you halp me i will learn so much from you in this project.. This is my elder brother's ID

link of the sensors i am getting in my country:

https://images-na.ssl-images-amazon.com/images/I/611SuZX5oYL._SL1000_.jpg

https://www.creatroninc.com/download/7615.jpg

**Comment by pgii** [comment]
Try it on aliexpress or ebay.
Age does not matter, the main thing is desire.
You have a long way to go.
The first thing to do is to understand the principle of the sensor and study the programming of microcontrollers.
Data visualization is the last step.

**Comment by graphicsguru1991** [comment]
You are good person and a great developer, learned so much from your creation.. i will be in touch with you if i have any doubts or stuck somewhere and learn more from you... Thank you sir

**Comment by pgii** [comment]
It's my pleasure. )

**Comment by graphicsguru1991** [comment]
Hi sir.. hope you are doing good.. sir i couldn't find the same module of wemos esp32 on online or in the electronic market in my country, but i have got NodeMCU esp32 and MPU9250 Sensors... Can you please help me with the pin connections and what changes i have to do on codes for these modules??

**Comment by pgii** [comment]
ESP32 will do.
They have the same pinout.
I originally debugged on something like this.
The MPU9250 is not so simple.
It is necessary to read the datasheet to find out the addresses and make the digital motion process (DMP) work.
But maybe you are lucky and it will work right away.
The contact connections will be the same.

**Comment by graphicsguru1991** [comment]
Im getting this issue , please help me to solve this issue in MPU9250_9Axis.h

specializing member 'MPU9250_::dmpInitialize' requires 'template<>' syntax

**Comment by pgii** [comment]
There is too little information available to reproduce the problem.
Give full details of the circumstances of the error.

**Comment by graphicsguru1991** [comment]
sir when i am trying to verify the ino file it is giving this error...

In file included from D:\Beaten Pixel mocap project\GyroMocapUE4-master\GyroSensor_MPU9250_ESP32\GyroSensor_MPU9250_ESP32.ino:3:0:
MPU9250_9Axis.h:331:9: error: specializing member 'MPU9250_<TwoWire>::dmpInitialize' requires 'template<>' syntax
 uint8_t MPU9250::dmpInitialize() {
         ^
In file included from c:\users\aman\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\xtensa-esp32-elf\include\c++\5.2.0\functional:53:0,
                 from C:\Users\aman\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\AsyncUDP\src/AsyncUDP.h:7,
                 from D:\Beaten Pixel mocap project\GyroMocapUE4-master\GyroSensor_MPU9250_ESP32\GyroSensor_MPU9250_ESP32.ino:6:
c:\users\aman\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\xtensa-esp32-elf\include\c++\5.2.0\typeinfo:39:37: error: expected declaration before end of line
exit status 1
specializing member 'MPU9250_<TwoWire>::dmpInitialize' requires 'template<>' syntax

**Comment by pgii** [comment]
Try changing the board type.

Checked on a clean installation.
Try to install the boards according to this instruction.
https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-windows-instructions/
Make sure that the MPU9250_ESP32_DMP folder is copied to the libraries folder.

**Comment by graphicsguru1991** [comment]
sir.. MPU9250_ESP32_DMP copy to which location in my system? where i have installed my Arduino software or somewhere inside GyroMocapUE4 folder?

**Comment by pgii** [comment]
Libraries are usually stored in C:\Users\UserName\Documents\Arduino\libraries

**Comment by graphicsguru1991** [comment]
success.. Thank you so much.... BTW which battery u have used sir?? I have 3.7v 450mah and 600mah lipo batteries.. can i  connect it or i have to use 7v or 5v lipo battery?

**Comment by graphicsguru1991** [comment]
Sir I am getting this message:

Invalid library found in C:\Users\aman\Documents\Arduino\libraries\Embedded_Template_Library: no headers files (.h) found in C:\Users\aman\Documents\Arduino\libraries\Embedded_Template_Library

**Comment by pgii** [comment]
I use LiPo 3.7v 580mAh.
Do not exceed voltage.
On Embedded_Template_Library I find it difficult to answer.

**Comment by graphicsguru1991** [comment]
3.7v battery on VIN right sir?? but when connecting it is giving 2.68v to 3v3 Pin for IMU sensor.. is it fine?

**Comment by pgii** [comment]
This is normal.
https://invensense.tdk.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf
Operating range of 2.4V to 3.6V

**Comment by graphicsguru1991** [comment]
Hardware part is Done from your help.. i have got  green status from sensor on sensor tuner. But sir in unreal its not moving anything.. how can i connect it to the unreal engine?? PLEASE HELP!!

**Comment by pgii** [comment]
Are you sure you are receiving data from DMP?
After the line
String gyroDataJSONString = GetGyroDataJSONString(sensorName, q.x, q.y, q.z, q.w);
Insert
Serial.print("Quat"); Serial.print("\t"); Serial.print(q.x); Serial.print("|"); Serial.print(q.y); Serial.print("|");Serial.print(q.z); Serial.print("|"); Serial.print(q.w); Serial.println("|");
And look in the port monitor to see what data is coming.

**Comment by graphicsguru1991** [comment]
no data in Serial monitor sir

**Comment by pgii** [comment]
Load https://github.com/pgii/GyroMocapUE4/tree/master/I2CScanner
See the result in port monitor.

**Comment by graphicsguru1991** [comment]
This error after loading I2CScanner

D:\Beaten Pixel mocap project\GyroMocapUE4-master\GyroSensor_MPU9250_ESP32\I2CScanner.ino: In function 'void setup()':
I2CScanner:3:6: error: redefinition of 'void setup()'
 void setup()

D:\Beaten Pixel mocap project\GyroMocapUE4-master\GyroSensor_MPU9250_ESP32\I2CScanner.ino: In function 'void loop()':
I2CScanner:10:6: error: redefinition of 'void loop()'
 void loop()

**Comment by pgii** [comment]
Make sure you have only one tab open in the IDE with your sketch and no more loop functions.
